[package]
name = "optimizer-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
butteraugli.workspace = true
crc32fast.workspace = true
flate2.workspace = true
image.workspace = true
mozjpeg-rs.workspace = true
png.workspace = true
quantette.workspace = true
rgb.workspace = true
serde.workspace = true
ssimulacra2.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
oxipng.workspace = true
